In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_excel(r"附件1(Appendix 1)2021-51MCM-Problem C.xlsx")
df

,时刻编号\n(Time number),传感器编号\n (Sensor number)\n 时刻 (Time),1,2,3,4,5,6,7,8,...,91,92,93,94,95,96,97,98,99,100
0,1,00:00:15,9.852378,211.773888,34.280285,3.420952,7.681146,3.840573,10.908712,11.7047,...,8.133741,14.951360,3.840573,201.730173,17.240383,247.751242,8.946132,5.615367,27.678858,53.0
1,2,00:00:30,9.852378,211.773888,34.609880,1.759244,7.681146,3.840573,10.908712,11.7047,...,5.773500,6.150462,3.840573,201.730173,11.761492,247.751242,7.284424,5.615367,27.678858,53.0
2,3,00:00:45,9.852378,211.773888,34.712214,2.174671,7.681146,3.840573,10.908712,11.7047,...,6.390486,3.180928,3.840573,201.730173,10.908712,247.751242,6.730521,5.615367,27.678858,53.0
3,4,00:01:00,9.852378,211.773888,35.040086,8.410692,7.681146,3.840573,10.908712,11.7047,...,15.363709,6.030450,3.840573,201.730173,10.908712,247.751242,7.284424,5.615367,27.678858,53.0
4,5,00:01:15,10.290884,211.773888,35.040086,7.141332,7.681146,3.840573,10.908712,11.7047,...,13.568142,14.762110,3.840573,201.730173,10.908712,247.751242,8.946132,5.615367,27.678858,53.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5514,5515,22:58:45,9.475416,215.283874,35.105660,-4.915283,7.681146,3.840573,17.466151,11.7047,...,7.218263,3.000910,3.840573,201.730173,17.466151,260.036192,5.819659,5.615367,25.353131,53.0
5515,5516,22:59:00,9.475416,215.283874,33.794173,3.359408,7.681146,3.840573,17.466151,11.7047,...,4.021014,12.523420,3.840573,201.730173,17.466151,260.036192,6.804375,5.615367,25.046368,53.0
5516,5517,22:59:15,9.475416,215.283874,33.531875,8.315298,7.681146,3.840573,17.466151,11.7047,...,7.213647,14.459002,3.840573,201.730173,17.466151,260.036192,7.001318,5.615367,25.046368,53.0
5517,5518,22:59:30,9.475416,215.283874,32.482685,8.307605,7.681146,3.840573,17.466151,11.7047,...,16.762314,28.612753,3.840573,201.730173,17.466151,260.036192,8.478392,5.615367,25.046368,53.0
5518,5519,22:59:45,9.881612,215.283874,35.695830,2.099279,7.681146,3.840573,17.466151,11.7047,...,16.716155,25.749384,3.840573,201.730173,17.466151,260.036192,8.182977,5.615367,25.046368,53.0

In [15]:

for i in [1, 3, 4, 9, 10, 15]:
    bzc = df[i].std()
    aver = df[i].mean()

    # print(bzc)
    # print(aver)

    print("{},{}".format(aver-3*bzc, aver+2*bzc))
    ser = df[i]

    bool_id = ((ser.mean() - 3 * ser.std()) <= ser)  &   (ser <= (ser.mean() + 3 * ser.std()))
    idx = bool_id[bool_id==False].index.to_list()
    tmp = df.iloc[idx, i+1]
    
    tmp2 = tmp.to_numpy()

    tmp2 = abs(tmp2-aver)
    
    tmp2 = (tmp2-tmp2.min())/(tmp2.max()-tmp2.min())
    
    tmp3 = pd.DataFrame(index=idx, data=tmp2)
    
    tmp3.to_excel('rate{}.xlsx'.format(i))

4.762742101278828,11.164332387540343
32.03365376322514,35.845342401181455
-2.920813315537133,11.916633455802177
16.360237453189715,22.889408281215893
-0.3126882212773957,0.3167502682965795
6.03470858322574,10.33343500610472